services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./dataset:/app/dataset
    environment:
      - FLASK_ENV=development
    command: ["flask", "--app", "main", "run", "--host=0.0.0.0", "--port=5000"]
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "run", "dev", "--", "--host"]
    depends_on:
      - backend

